import { Country, Locale } from "@laptopoutlet-packages/types";

export const DEFAULT_LOCALE = Locale.Es;
export const IS_ADMIN =
	process.env.NEXT_PUBLIC_APP_NAME === "Laptop Outlet Admin";

export const COUNTRIES_ES = [
	{ name: "Afganistán", code: Country.Af },
	{ name: "Albania", code: Country.Al },
	{ name: "Argelia", code: Country.Dz },
	{ name: "Samoa Americana", code: Country.As },
	{ name: "Andorra", code: Country.Ad },
	{ name: "Angola", code: Country.Ao },
	{ name: "Anguila", code: Country.Ai },
	{ name: "Antártida", code: Country.Aq },
	{ name: "Antigua y Barbuda", code: Country.Ag },
	{ name: "Argentina", code: Country.Ar },
	{ name: "Armenia", code: Country.Am },
	{ name: "Aruba", code: Country.Aw },
	{ name: "Australia", code: Country.Au },
	{ name: "Austria", code: Country.At },
	{ name: "Azerbaiyán", code: Country.Az },
	{ name: "Bahamas", code: Country.Bs },
	{ name: "Baréin", code: Country.Bh },
	{ name: "Bangladesh", code: Country.Bd },
	{ name: "Barbados", code: Country.Bb },
	{ name: "Bielorrusia", code: Country.By },
	{ name: "Bélgica", code: Country.Be },
	{ name: "Belice", code: Country.Bz },
	{ name: "Benin", code: Country.Bj },
	{ name: "Bermudas", code: Country.Bm },
	{ name: "Bután", code: Country.Bt },
	{ name: "Bolivia", code: Country.Bo },
	{ name: "Bosnia y Herzegovina", code: Country.Ba },
	{ name: "Botswana", code: Country.Bw },
	{ name: "Isla Bouvet", code: Country.Bv },
	{ name: "Brasil", code: Country.Br },
	{ name: "Brunei Darussalam", code: Country.Bn },
	{ name: "Bulgaria", code: Country.Bg },
	{ name: "Burkina Faso", code: Country.Bf },
	{ name: "Burundi", code: Country.Bi },
	{ name: "Camboya", code: Country.Kh },
	{ name: "Camerún", code: Country.Cm },
	{ name: "Canadá", code: Country.Ca },
	{ name: "Cabo Verde", code: Country.Cv },
	{ name: "Islas Caimán", code: Country.Ky },
	{ name: "República Centroafricana", code: Country.Cf },
	{ name: "Chad", code: Country.Td },
	{ name: "Chile", code: Country.Cl },
	{ name: "China", code: Country.Cn },
	{ name: "Isla de Navidad", code: Country.Cx },
	{ name: "Islas Cocos (Keeling)", code: Country.Cc },
	{ name: "Colombia", code: Country.Co },
	{ name: "Comoras", code: Country.Km },
	{ name: "Congo", code: Country.Cg },
	{ name: "República Democrática del Congo", code: Country.Cd },
	{ name: "Islas Cook", code: Country.Ck },
	{ name: "Costa Rica", code: Country.Cr },
	{ name: `Costa de Marfil`, code: Country.Ci },
	{ name: "Croacia", code: Country.Hr },
	{ name: "Cuba", code: Country.Cu },
	{ name: "Chipre", code: Country.Cy },
	{ name: "República Checa", code: Country.Cz },
	{ name: "Dinamarca", code: Country.Dk },
	{ name: "Djibouti", code: Country.Dj },
	{ name: "Dominica", code: Country.Dm },
	{ name: "República Dominicana", code: Country.Do },
	{ name: "Ecuador", code: Country.Ec },
	{ name: "Egipto", code: Country.Eg },
	{ name: "El Salvador", code: Country.Sv },
	{ name: "Guinea Ecuatorial", code: Country.Gq },
	{ name: "Eritrea", code: Country.Er },
	{ name: "Estonia", code: Country.Ee },
	{ name: "Etiopía", code: Country.Et },
	{ name: "Islas Falkland (Malvinas)", code: Country.Fk },
	{ name: "Islas Feroe", code: Country.Fo },
	{ name: "Fiji", code: Country.Fj },
	{ name: "Finlandia", code: Country.Fi },
	{ name: "Francia", code: Country.Fr },
	{ name: "Guayana Francesa", code: Country.Gf },
	{ name: "Polinesia francesa", code: Country.Pf },
	{ name: "Territorios Australes Franceses", code: Country.Tf },
	{ name: "Gabón", code: Country.Ga },
	{ name: "Gambia", code: Country.Gm },
	{ name: "Georgia", code: Country.Ge },
	{ name: "Alemania", code: Country.De },
	{ name: "Ghana", code: Country.Gh },
	{ name: "Gibraltar", code: Country.Gi },
	{ name: "Grecia", code: Country.Gr },
	{ name: "Groenlandia", code: Country.Gl },
	{ name: "Granada", code: Country.Gd },
	{ name: "Guadalupe", code: Country.Gp },
	{ name: "Guam", code: Country.Gu },
	{ name: "Guatemala", code: Country.Gt },
	{ name: "Guernsey", code: Country.Gg },
	{ name: "Guinea", code: Country.Gn },
	{ name: "Guinea-Bissau", code: Country.Gw },
	{ name: "Guyana", code: Country.Gy },
	{ name: "Haití", code: Country.Ht },
	{ name: "Islas Heard y Mcdonald", code: Country.Hm },
	{ name: "Santa Sede (Vaticano)", code: Country.Va },
	{ name: "Honduras", code: Country.Hn },
	{ name: "Hong Kong", code: Country.Hk },
	{ name: "Hungría", code: Country.Hu },
	{ name: "Islandia", code: Country.Is },
	{ name: "India", code: Country.In },
	{ name: "Indonesia", code: Country.Id },
	{ name: "Irán", code: Country.Ir },
	{ name: "Irak", code: Country.Iq },
	{ name: "Irlanda", code: Country.Ie },
	{ name: "Isla de Man", code: Country.Im },
	{ name: "Israel", code: Country.Il },
	{ name: "Italia", code: Country.It },
	{ name: "Jamaica", code: Country.Jm },
	{ name: "Japón", code: Country.Jp },
	{ name: "Jersey", code: Country.Je },
	{ name: "Jordan", code: Country.Jo },
	{ name: "Kazajstán", code: Country.Kz },
	{ name: "Kenia", code: Country.Ke },
	{ name: "Kiribati", code: Country.Ki },
	{ name: "Corea del Norte", code: Country.Kp },
	{ name: "Corea del Sur", code: Country.Kr },
	{ name: "Kuwait", code: Country.Kw },
	{ name: "Kirguistán", code: Country.Kg },
	{ name: `Laos`, code: Country.La },
	{ name: "Letonia", code: Country.Lv },
	{ name: "Líbano", code: Country.Lb },
	{ name: "Lesoto", code: Country.Ls },
	{ name: "Liberia", code: Country.Lr },
	{ name: "República Árabe Libia", code: Country.Ly },
	{ name: "Liechtenstein", code: Country.Li },
	{ name: "Lituania", code: Country.Lt },
	{ name: "Luxemburgo", code: Country.Lu },
	{ name: "Macao", code: Country.Mo },
	{ name: "Macedonia", code: Country.Mk },
	{ name: "Madagascar", code: Country.Mg },
	{ name: "Malawi", code: Country.Mw },
	{ name: "Malasia", code: Country.My },
	{ name: "Maldivas", code: Country.Mv },
	{ name: "Mali", code: Country.Ml },
	{ name: "Malta", code: Country.Mt },
	{ name: "Islas Marshall", code: Country.Mh },
	{ name: "Martinica", code: Country.Mq },
	{ name: "Mauritania", code: Country.Mr },
	{ name: "Mauricio", code: Country.Mu },
	{ name: "Mayotte", code: Country.Yt },
	{ name: "México", code: Country.Mx },
	{ name: "Micronesia", code: Country.Fm },
	{ name: "Moldavia", code: Country.Md },
	{ name: "Mónaco", code: Country.Mc },
	{ name: "Mongolia", code: Country.Mn },
	{ name: "Montenegro", code: Country.Me },
	{ name: "Montserrat", code: Country.Ms },
	{ name: "Marruecos", code: Country.Ma },
	{ name: "Mozambique", code: Country.Mz },
	{ name: "Myanmar", code: Country.Mm },
	{ name: "Namibia", code: Country.Na },
	{ name: "Nauru", code: Country.Nr },
	{ name: "Nepal", code: Country.Np },
	{ name: "Países Bajos", code: Country.Nl },
	{ name: "Nueva Caledonia", code: Country.Nc },
	{ name: "Nueva Zelanda", code: Country.Nz },
	{ name: "Nicaragua", code: Country.Ni },
	{ name: "Níger", code: Country.Ne },
	{ name: "Nigeria", code: Country.Ng },
	{ name: "Niue", code: Country.Nu },
	{ name: "Isla Norfolk", code: Country.Nf },
	{ name: "Islas Marianas del Norte", code: Country.Mp },
	{ name: "Noruega", code: Country.No },
	{ name: "Omán", code: Country.Om },
	{ name: "Pakistán", code: Country.Pk },
	{ name: "Palau", code: Country.Pw },
	{ name: "Territorio Palestino, Ocupado", code: Country.Ps },
	{ name: "Panamá", code: Country.Pa },
	{ name: "Papúa Nueva Guinea", code: Country.Pg },
	{ name: "Paraguay", code: Country.Py },
	{ name: "Perú", code: Country.Pe },
	{ name: "Filipinas", code: Country.Ph },
	{ name: "Pitcairn", code: Country.Pn },
	{ name: "Polonia", code: Country.Pl },
	{ name: "Portugal", code: Country.Pt },
	{ name: "Puerto Rico", code: Country.Pr },
	{ name: "Qatar", code: Country.Qa },
	{ name: "Reunión", code: Country.Re },
	{ name: "Rumania", code: Country.Ro },
	{ name: "Federación de Rusia", code: Country.Ru },
	{ name: "RWANDA", code: Country.Rw },
	{ name: "Santa Helena", code: Country.Sh },
	{ name: "Saint Kitts y Nevis", code: Country.Kn },
	{ name: "Santa Lucía", code: Country.Lc },
	{ name: "San Pedro y Miquelón", code: Country.Pm },
	{ name: "San Vicente y las Granadinas", code: Country.Vc },
	{ name: "Samoa", code: Country.Ws },
	{ name: "San Marino", code: Country.Sm },
	{ name: "Santo Tomé y Príncipe", code: Country.St },
	{ name: "Arabia Saudita", code: Country.Sa },
	{ name: "Senegal", code: Country.Sn },
	{ name: "Serbia", code: Country.Rs },
	{ name: "Seychelles", code: Country.Sc },
	{ name: "Sierra Leona", code: Country.Sl },
	{ name: "Singapur", code: Country.Sg },
	{ name: "Eslovaquia", code: Country.Sk },
	{ name: "Eslovenia", code: Country.Si },
	{ name: "Islas Salomón", code: Country.Sb },
	{ name: "Somalia", code: Country.So },
	{ name: "Sudáfrica", code: Country.Za },
	{ name: "España", code: Country.Es },
	{ name: "Sri Lanka", code: Country.Lk },
	{ name: "Sudán", code: Country.Sd },
	{ name: "Surinam", code: Country.Sr },
	{ name: "Svalbard y Jan Mayen", code: Country.Sj },
	{ name: "Swazilandia", code: Country.Sz },
	{ name: "Suecia", code: Country.Se },
	{ name: "Suiza", code: Country.Ch },
	{ name: "República Árabe Siria", code: Country.Sy },
	{ name: "Taiwán", code: Country.Tw },
	{ name: "Tayikistán", code: Country.Tj },
	{ name: "Tanzania", code: Country.Tz },
	{ name: "Tailandia", code: Country.Th },
	{ name: "Timor-Leste", code: Country.Tl },
	{ name: "Togo", code: Country.Tg },
	{ name: "Tokelau", code: Country.Tk },
	{ name: "Tonga", code: Country.To },
	{ name: "Trinidad y Tobago", code: Country.Tt },
	{ name: "Túnez", code: Country.Tn },
	{ name: "Turquía", code: Country.Tr },
	{ name: "Turkmenistán", code: Country.Tm },
	{ name: "Islas Turcas y Caicos", code: Country.Tc },
	{ name: "Tuvalu", code: Country.Tv },
	{ name: "Uganda", code: Country.Ug },
	{ name: "Ucrania", code: Country.Ua },
	{ name: "Emiratos Árabes Unidos", code: Country.Ae },
	{ name: "Reino Unido", code: Country.Gb },
	{ name: "Estados Unidos", code: Country.Us },
	{ name: "Uruguay", code: Country.Uy },
	{ name: "Uzbekistán", code: Country.Uz },
	{ name: "Vanuatu", code: Country.Vu },
	{ name: "Venezuela", code: Country.Ve },
	{ name: "Vietnam", code: Country.Vn },
	{ name: "Islas Vírgenes Británicas", code: Country.Vg },
	{ name: "Islas Vírgenes, EE. UU.", code: Country.Vi },
	{ name: "Wallis y Futuna", code: Country.Wf },
	{ name: "Sáhara Occidental", code: Country.Eh },
	{ name: "Yemen", code: Country.Ye },
	{ name: "Zambia", code: Country.Zm },
	{ name: "Zimbabwe", code: Country.Zw },
];

export const COUNTRIES_EN = [
	{ name: "Afghanistan", code: Country.Af },
	{ name: "Albania", code: Country.Al },
	{ name: "Algeria", code: Country.Dz },
	{ name: "American Samoa", code: Country.As },
	{ name: "Andorra", code: Country.Ad },
	{ name: "Angola", code: Country.Ao },
	{ name: "Anguilla", code: Country.Ai },
	{ name: "Antarctica", code: Country.Aq },
	{ name: "Antigua and Barbuda", code: Country.Ag },
	{ name: "Argentina", code: Country.Ar },
	{ name: "Armenia", code: Country.Am },
	{ name: "Aruba", code: Country.Aw },
	{ name: "Australia", code: Country.Au },
	{ name: "Austria", code: Country.At },
	{ name: "Azerbaijan", code: Country.Az },
	{ name: "Bahamas", code: Country.Bs },
	{ name: "Bahrain", code: Country.Bh },
	{ name: "Bangladesh", code: Country.Bd },
	{ name: "Barbados", code: Country.Bb },
	{ name: "Belarus", code: Country.By },
	{ name: "Belgium", code: Country.Be },
	{ name: "Belize", code: Country.Bz },
	{ name: "Benin", code: Country.Bj },
	{ name: "Bermuda", code: Country.Bm },
	{ name: "Bhutan", code: Country.Bt },
	{ name: "Bolivia", code: Country.Bo },
	{ name: "Bosnia and Herzegovina", code: Country.Ba },
	{ name: "Botswana", code: Country.Bw },
	{ name: "Bouvet Island", code: Country.Bv },
	{ name: "Brazil", code: Country.Br },
	{ name: "Brunei Darussalam", code: Country.Bn },
	{ name: "Bulgaria", code: Country.Bg },
	{ name: "Burkina Faso", code: Country.Bf },
	{ name: "Burundi", code: Country.Bi },
	{ name: "Cambodia", code: Country.Kh },
	{ name: "Cameroon", code: Country.Cm },
	{ name: "Canada", code: Country.Ca },
	{ name: "Cape Verde", code: Country.Cv },
	{ name: "Cayman Islands", code: Country.Ky },
	{ name: "Central African Republic", code: Country.Cf },
	{ name: "Chad", code: Country.Td },
	{ name: "Chile", code: Country.Cl },
	{ name: "China", code: Country.Cn },
	{ name: "Christmas Island", code: Country.Cx },
	{ name: "Cocos (Keeling) Islands", code: Country.Cc },
	{ name: "Colombia", code: Country.Co },
	{ name: "Comoros", code: Country.Km },
	{ name: "Congo", code: Country.Cg },
	{ name: "Democratic Republic of the Congo", code: Country.Cd },
	{ name: "Cook Islands", code: Country.Ck },
	{ name: "Costa Rica", code: Country.Cr },
	{ name: `Cote D"Ivoire`, code: Country.Ci },
	{ name: "Croatia", code: Country.Hr },
	{ name: "Cuba", code: Country.Cu },
	{ name: "Cyprus", code: Country.Cy },
	{ name: "Czech Republic", code: Country.Cz },
	{ name: "Denmark", code: Country.Dk },
	{ name: "Djibouti", code: Country.Dj },
	{ name: "Dominica", code: Country.Dm },
	{ name: "Dominican Republic", code: Country.Do },
	{ name: "Ecuador", code: Country.Ec },
	{ name: "Egypt", code: Country.Eg },
	{ name: "El Salvador", code: Country.Sv },
	{ name: "Equatorial Guinea", code: Country.Gq },
	{ name: "Eritrea", code: Country.Er },
	{ name: "Estonia", code: Country.Ee },
	{ name: "Ethiopia", code: Country.Et },
	{ name: "Falkland Islands (Malvinas)", code: Country.Fk },
	{ name: "Faroe Islands", code: Country.Fo },
	{ name: "Fiji", code: Country.Fj },
	{ name: "Finland", code: Country.Fi },
	{ name: "France", code: Country.Fr },
	{ name: "French Guiana", code: Country.Gf },
	{ name: "French Polynesia", code: Country.Pf },
	{ name: "French Southern Territories", code: Country.Tf },
	{ name: "Gabon", code: Country.Ga },
	{ name: "Gambia", code: Country.Gm },
	{ name: "Georgia", code: Country.Ge },
	{ name: "Germany", code: Country.De },
	{ name: "Ghana", code: Country.Gh },
	{ name: "Gibraltar", code: Country.Gi },
	{ name: "Greece", code: Country.Gr },
	{ name: "Greenland", code: Country.Gl },
	{ name: "Grenada", code: Country.Gd },
	{ name: "Guadeloupe", code: Country.Gp },
	{ name: "Guam", code: Country.Gu },
	{ name: "Guatemala", code: Country.Gt },
	{ name: "Guernsey", code: Country.Gg },
	{ name: "Guinea", code: Country.Gn },
	{ name: "Guinea-Bissau", code: Country.Gw },
	{ name: "Guyana", code: Country.Gy },
	{ name: "Haiti", code: Country.Ht },
	{ name: "Heard Island and Mcdonald Islands", code: Country.Hm },
	{ name: "Holy See (Vatican City State)", code: Country.Va },
	{ name: "Honduras", code: Country.Hn },
	{ name: "Hong Kong", code: Country.Hk },
	{ name: "Hungary", code: Country.Hu },
	{ name: "Iceland", code: Country.Is },
	{ name: "India", code: Country.In },
	{ name: "Indonesia", code: Country.Id },
	{ name: "Iran", code: Country.Ir },
	{ name: "Iraq", code: Country.Iq },
	{ name: "Ireland", code: Country.Ie },
	{ name: "Isle of Man", code: Country.Im },
	{ name: "Israel", code: Country.Il },
	{ name: "Italy", code: Country.It },
	{ name: "Jamaica", code: Country.Jm },
	{ name: "Japan", code: Country.Jp },
	{ name: "Jersey", code: Country.Je },
	{ name: "Jordan", code: Country.Jo },
	{ name: "Kazakhstan", code: Country.Kz },
	{ name: "Kenya", code: Country.Ke },
	{ name: "Kiribati", code: Country.Ki },
	{ name: "North Korea", code: Country.Kp },
	{ name: "South Korea", code: Country.Kr },
	{ name: "Kuwait", code: Country.Kw },
	{ name: "Kyrgyzstan", code: Country.Kg },
	{ name: `Lao People"S Democratic Republic`, code: Country.La },
	{ name: "Latvia", code: Country.Lv },
	{ name: "Lebanon", code: Country.Lb },
	{ name: "Lesotho", code: Country.Ls },
	{ name: "Liberia", code: Country.Lr },
	{ name: "Libyan Arab Jamahiriya", code: Country.Ly },
	{ name: "Liechtenstein", code: Country.Li },
	{ name: "Lithuania", code: Country.Lt },
	{ name: "Luxembourg", code: Country.Lu },
	{ name: "Macao", code: Country.Mo },
	{ name: "Macedonia", code: Country.Mk },
	{ name: "Madagascar", code: Country.Mg },
	{ name: "Malawi", code: Country.Mw },
	{ name: "Malaysia", code: Country.My },
	{ name: "Maldives", code: Country.Mv },
	{ name: "Mali", code: Country.Ml },
	{ name: "Malta", code: Country.Mt },
	{ name: "Marshall Islands", code: Country.Mh },
	{ name: "Martinique", code: Country.Mq },
	{ name: "Mauritania", code: Country.Mr },
	{ name: "Mauritius", code: Country.Mu },
	{ name: "Mayotte", code: Country.Yt },
	{ name: "Mexico", code: Country.Mx },
	{ name: "Micronesia", code: Country.Fm },
	{ name: "Moldova", code: Country.Md },
	{ name: "Monaco", code: Country.Mc },
	{ name: "Mongolia", code: Country.Mn },
	{ name: "Montenegro", code: Country.Me },
	{ name: "Montserrat", code: Country.Ms },
	{ name: "Morocco", code: Country.Ma },
	{ name: "Mozambique", code: Country.Mz },
	{ name: "Myanmar", code: Country.Mm },
	{ name: "Namibia", code: Country.Na },
	{ name: "Nauru", code: Country.Nr },
	{ name: "Nepal", code: Country.Np },
	{ name: "Netherlands", code: Country.Nl },
	{ name: "New Caledonia", code: Country.Nc },
	{ name: "New Zealand", code: Country.Nz },
	{ name: "Nicaragua", code: Country.Ni },
	{ name: "Niger", code: Country.Ne },
	{ name: "Nigeria", code: Country.Ng },
	{ name: "Niue", code: Country.Nu },
	{ name: "Norfolk Island", code: Country.Nf },
	{ name: "Northern Mariana Islands", code: Country.Mp },
	{ name: "Norway", code: Country.No },
	{ name: "Oman", code: Country.Om },
	{ name: "Pakistan", code: Country.Pk },
	{ name: "Palau", code: Country.Pw },
	{ name: "Palestinian Territory, Occupied", code: Country.Ps },
	{ name: "Panama", code: Country.Pa },
	{ name: "Papua New Guinea", code: Country.Pg },
	{ name: "Paraguay", code: Country.Py },
	{ name: "Peru", code: Country.Pe },
	{ name: "Philippines", code: Country.Ph },
	{ name: "Pitcairn", code: Country.Pn },
	{ name: "Poland", code: Country.Pl },
	{ name: "Portugal", code: Country.Pt },
	{ name: "Puerto Rico", code: Country.Pr },
	{ name: "Qatar", code: Country.Qa },
	{ name: "Reunion", code: Country.Re },
	{ name: "Romania", code: Country.Ro },
	{ name: "Russian Federation", code: Country.Ru },
	{ name: "RWANDA", code: Country.Rw },
	{ name: "Saint Helena", code: Country.Sh },
	{ name: "Saint Kitts and Nevis", code: Country.Kn },
	{ name: "Saint Lucia", code: Country.Lc },
	{ name: "Saint Pierre and Miquelon", code: Country.Pm },
	{ name: "Saint Vincent and the Grenadines", code: Country.Vc },
	{ name: "Samoa", code: Country.Ws },
	{ name: "San Marino", code: Country.Sm },
	{ name: "Sao Tome and Principe", code: Country.St },
	{ name: "Saudi Arabia", code: Country.Sa },
	{ name: "Senegal", code: Country.Sn },
	{ name: "Serbia", code: Country.Rs },
	{ name: "Seychelles", code: Country.Sc },
	{ name: "Sierra Leone", code: Country.Sl },
	{ name: "Singapore", code: Country.Sg },
	{ name: "Slovakia", code: Country.Sk },
	{ name: "Slovenia", code: Country.Si },
	{ name: "Solomon Islands", code: Country.Sb },
	{ name: "Somalia", code: Country.So },
	{ name: "South Africa", code: Country.Za },
	{ name: "Spain", code: Country.Es },
	{ name: "Sri Lanka", code: Country.Lk },
	{ name: "Sudan", code: Country.Sd },
	{ name: "Suriname", code: Country.Sr },
	{ name: "Svalbard and Jan Mayen", code: Country.Sj },
	{ name: "Swaziland", code: Country.Sz },
	{ name: "Sweden", code: Country.Se },
	{ name: "Switzerland", code: Country.Ch },
	{ name: "Syrian Arab Republic", code: Country.Sy },
	{ name: "Taiwan", code: Country.Tw },
	{ name: "Tajikistan", code: Country.Tj },
	{ name: "Tanzania", code: Country.Tz },
	{ name: "Thailand", code: Country.Th },
	{ name: "Timor-Leste", code: Country.Tl },
	{ name: "Togo", code: Country.Tg },
	{ name: "Tokelau", code: Country.Tk },
	{ name: "Tonga", code: Country.To },
	{ name: "Trinidad and Tobago", code: Country.Tt },
	{ name: "Tunisia", code: Country.Tn },
	{ name: "Turkey", code: Country.Tr },
	{ name: "Turkmenistan", code: Country.Tm },
	{ name: "Turks and Caicos Islands", code: Country.Tc },
	{ name: "Tuvalu", code: Country.Tv },
	{ name: "Uganda", code: Country.Ug },
	{ name: "Ukraine", code: Country.Ua },
	{ name: "United Arab Emirates", code: Country.Ae },
	{ name: "United Kingdom", code: Country.Gb },
	{ name: "United States", code: Country.Us },
	{ name: "Uruguay", code: Country.Uy },
	{ name: "Uzbekistan", code: Country.Uz },
	{ name: "Vanuatu", code: Country.Vu },
	{ name: "Venezuela", code: Country.Ve },
	{ name: "Vietnam", code: Country.Vn },
	{ name: "Virgin Islands, British", code: Country.Vg },
	{ name: "Virgin Islands, U.S.", code: Country.Vi },
	{ name: "Wallis and Futuna", code: Country.Wf },
	{ name: "Western Sahara", code: Country.Eh },
	{ name: "Yemen", code: Country.Ye },
	{ name: "Zambia", code: Country.Zm },
	{ name: "Zimbabwe", code: Country.Zw },
];

export const COUNTRIES = {
	[Locale.Es]: COUNTRIES_ES,
	[Locale.En]: COUNTRIES_EN,
};
